[package]
name = "sourceselector-ui"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.33.3"
egui = "0.33.3"
egui_extras = { version = "0.33.3", features = ["all_loaders"] }
image = { version = "0.25.9" }
libsourceselector = { version = "0.1.0", path = "../libsourceselector" }
